### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vperilla** [mmatvein/bevy_liquidfun#1]
When I try to build using:

cargo build

I received this error:
```
   Compiling bevy_liquidfun v0.1.0 (/home/perilla/repos/bevy_liquidfun)
error[E0425]: cannot find function, tuple struct or tuple variant `CreateRevoluteJoint` in module `ffi`
  --> src/dynamics/joints/revolute_joint.rs:71:34
   |
71 |             let ffi_joint = ffi::CreateRevoluteJoint(
   |                                  ^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `CreatePrismaticJoint` in module `ffi`
  --> src/dynamics/joints/prismatic_joint.rs:71:34
   |
71 |             let ffi_joint = ffi::CreatePrismaticJoint(
   |                                  ^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `bevy_liquidfun` (lib) due to 2 previous errors
```

**Comment by mmatvein** [comment]
Hey! This crate and the underlying libliquidfun-sys wrapper (that I am also working on) are very much works in progress. Try updating libliquidfun-sys with `cargo update -p libliquidfun-sys` to get the latest git updates. Let me know if that helps! Your feedback on the API is very welcome.

**Comment by vperilla** [comment]
Ok, that worked, thanks.  In the past I worked with Box2d on some projects, now I'm learning Rust and having fun with Box2d at the same time.

**Comment by mmatvein** [comment]
I have now published the libliquidfun-sys package as a crate on crates.io and switched bevy_liquidfun to use it. This way the crates should stay better in sync. 😊

I'm also dabbling around in learning Rust (coming from Unity/C#). It's been fun so far, even though creating a C++ wrapper as the first thing is not necessarily the easiest way to start. 😄
